name: test-package-deploy-pipeline #MWC
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: "test"
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip  # installs pip and upgrades to the latest version
          pip install -r requirements.txt;

      - name: Install pytest and dependencies
        run: |
          pip install pytest

      # Run tests
      - name: Run tests with pytest
        run: |
          python -m pytest

  package:
    name: "package"
    runs-on: ubuntu-latest
    needs: test

    steps:
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt;

      # package application into BUILD directory
      - name: Create BUILD directory and copy necessary application files
        run: |
          mkdir BUILD
          cp -r static BUILD/static  # copy the static directory and contents
          cp -r templates BUILD/templates  # copy the templates directory and contents
          cp -r app.py BUILD/app.py
          cp -r requirements.txt BUILD/requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            ./BUILD

  deploy:
    runs-on: ubuntu-latest
    needs: package
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: "flask-tests"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E4A71BE1C9894E5C840B74AA44F135B1 }}
